// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  ///get platform
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  ///web options
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUGiOdOWx10mb8GsarIQMSBzesIlvBZoM',
    appId: '1:970082532562:web:30fae0eb58dd5caec0410b',
    messagingSenderId: '970082532562',
    projectId: 'market-project-admin',
    authDomain: 'market-project-admin.firebaseapp.com',
    storageBucket: 'market-project-admin.appspot.com',
    measurementId: 'G-0TPFNE0MFB',
  );

  ///android options
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSFHxgyE4TLegdhydwlqZtzwBnLVicWiM',
    appId: '1:970082532562:android:d5e1d22aed4bdb3ec0410b',
    messagingSenderId: '970082532562',
    projectId: 'market-project-admin',
    storageBucket: 'market-project-admin.appspot.com',
  );

  /// ios options
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3d53VjMhubpBjTf9hrcvmNtbuCEAbum0',
    appId: '1:970082532562:ios:8f5f803194057ae4c0410b',
    messagingSenderId: '970082532562',
    projectId: 'market-project-admin',
    storageBucket: 'market-project-admin.appspot.com',
    iosClientId: '970082532562-saprvd33efcopchaldd95iu52cr3aj9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketProjectAdmin',
  );
}
